create:
  fields:
    image:
      required: true
      selector:
        text:
    name:
      required: true
      selector:
        text:
    network:
      required: false
      network:
        text:
    ports:
      required: false
      selector:
        object:
    volumes:
      required: false
      selector:
        object:
    restart_policy:
      required: false
      selector:
        select:
          options:
            - "no"
            - "always"
            - "on-failure"
            - "unless-stopped"
